#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/product
#    username: root
#    password: pass@word1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-sr:8763/eureka/

server:
  port: 9091

spring:
  application:
    name: Product

  datasource:
    url: jdbc:mysql://mysqldb-prod:3306/product
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

